default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: train_development

test:
  <<: *default
  database: train_test

production:
  <<: *default
  database: train_production
  username: train
  password: <%= ENV['TRAIN_DATABASE_PASSWORD'] %>
